repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: bash -c 'gofmt -w $(find . -name "*.go")'
        language: system
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
